
USE_OPTIMISTIC_VALUE_ITERATION = False
PRINT_OVI_ERROR_BOUNDS = True
RELATIVE_ERROR_TARGET = 0.0001
UPPER_BOUND_HEURISTIC = 0.0001

USE_EVOLUTION_VALUE_ITERATION = True
PRINT_EVI_STEP = False
PRINT_EVI_RESULT = True
RANDOMNESS_OUTSIDE_OF_DISTRIBUTIONS = 1
RANDOMNESS_OF_STEP_LOWER_BOUND = 1
RANDOMNESS_OF_STEP_UPPER_BOUND = 1.5
