
USE_OPTIMISTIC_VALUE_ITERATION = False
PRINT_OVI_ERROR_BOUNDS = True
RELATIVE_ERROR_TARGET = 0.1
UPPER_BOUND_HEURISTIC = 0.1

USE_EVOLUTION_VALUE_ITERATION = True
PRINT_EVI_STEP = False
PRINT_EVI_RESULT = True
RANDOMNESS_OUTSIDE_OF_DISTRIBUTIONS = -0.1
RANDOMNESS_OF_STEP = 0.35